---
- name: spawn-fcgi | install and configure spawn-fcgi
  hosts: vm1
  become: true

  tasks:
    - name: install spawn-fcgi
      apt:
        name:
          - spawn-fcgi
          - php
          - php-cgi
          - php-cli
          - apache2
          - libapache2-mod-fcgid
        state: latest
        
    - name: configure spawn-fcgi
      template:
        src: templates/fcgi.conf
        dest: /etc/spawn-fcgi/fcgi.conf
        
    - name: configure spawn-fcgi.service
      template:
        src: templates/fcgi.conf
        dest: /etc/spawn-fcgi/fcgi.conf

  handlers:
    - name: start spawn-fcgi
      systemd:
        name: spawn-fcgi
        state: started
        enabled: yes
