---
- name: service that will monitor the registration of an item on a keyword document every 30 seconds
  hosts: vm1
  become: true

  tasks:
    - name: Copy log file
      template:
        src: templates/watchlog.log
        dest: /var/log/watchlog.log
    
    - name: Copy Configuration file
      template:
        src: templates/watchlog
        dest: /etc/default/watchlog
        
    - name: Copy scripts watchlog
      template:
        src: templates/watchlog.sh
        dest: /opt/watchlog.sh

    - name: Stop Service If Running One
      shell: chmod +x /opt/watchlog.sh

    - name: Copy service
      template:
        src: templates/watchlog.service
        dest: /etc/systemd/system/watchlog.service

    - name: Copy timer
      template:
        src: templates/watchlog.timer
        dest: /etc/systemd/system/watchlog.timer

  handlers:
    - name: started watchlog
      systemd:
        name: nginx
        state: started
        enabled: yes
    - name: reload watchlog
      systemd:
        name: watchlog
        state: reload
